config/routes.rb
Rails.application.routes.draw do
  resources :details
  root 'details#index'
  get 'report' => 'details#get_report', as: :report 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
	validates :shop_name, presence: true
	validates :status, presence: true
	# validates_format_of :phone, :with =>  /\d[0-9]\)*\z/ , :message => "Only positive number without spaces are allowed"
	default_scope -> { order(updated_at: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]

  # GET /details
  # GET /details.json
  def index
    #@details = Detail.all.order('created_at DESC')
    @details = Detail.paginate(page: params[:page], per_page: 5)
  end

  def get_report
    @todays_details = Detail.where("created_at >= ?", Time.zone.now.beginning_of_day)
      if @todays_details.blank?
        flash[:alert] = "You have not made today's entry. Please make an entry now!"
        redirect_to new_detail_path and return
      end
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrderPdf.new(@todays_details, view_context)
        pdf.render_file "#{Rails.root}/lib/attachments/ramesh_daily_report.pdf"
        send_data pdf.render, filename: "#{Rails.root}/lib/attachments/ramesh_daily_report.pdf", type: "application/pdf",disposition: "inline"
      end
    end
    StoryMailer.daily_story.deliver_now
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)
      if @detail.save
        flash[:success] = "Detail was successfully created!"
        redirect_to @detail
      else
        render 'new'
      end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    if @detail.update(detail_params)
      flash[:success] = "Detail was successfully updated!"
      redirect_to detail_path(@detail)
    else
      render 'edit'
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    flash[:success] = "Detail was successfully destroyed!"
    redirect_to details_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:shop_name, :cust_name, :phone, :address, :status, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= render 'shared/errors', obj: @detail %>
<div class="row">
  <div class="col-md-12">
     <%= form_for(@detail, :html => {class: "form-horizontal", role: "form"}) do |f| %>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :date %>
        </div>
        <div class="col-md-8">
          <%= f.date_select :date, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :shop_name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :shop_name, class: "form-control", placeholder: "Name of the shop", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :cust_name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :cust_name, class: "form-control", placeholder: "Name of the customer", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :phone %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :phone, class: "form-control", placeholder: "Contact number of the customer", autofocus: true %>
        </div>
      </div>


      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :address %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :address, rows: 5, class: "form-control", placeholder: "Enter the full address" %>
        </div>
      </div>

       <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :status %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :status, rows: 20, class: "form-control", placeholder: "Please type in the status" %>
        </div>
      </div>


     
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch"> [<%= link_to 'Cancel Request and return to homepage', root_path %>] </div>
  </div>
</div>

app/views/details/edit.html.erb
<h1>Editing Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Show', @detail %> 

app/views/details/index.html.erb
<div align="center">
  <%= will_paginate %>
</div>

<p id="notice"><%= notice %></p>

<h1>Details</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Shop name</th>
      <th>Cust name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.date.strftime("%d/%m/%Y") if !detail.date.nil? %></td>
        <td><%= detail.shop_name %></td>
        <td><%= detail.cust_name %></td>
        <td><%= detail.phone %></td>
        <!-- <td><%#= detail.address %></td> -->
        <td><%= truncate(detail.address, length: 50) %></td>
        <!-- <td><%#= detail.status %></td> -->
        <td><%= truncate(detail.status, length: 150) %></td>
        <td><%= link_to 'Show', detail %></td>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div align="center">
  <%= will_paginate %>
</div>  

<br>

<%#= link_to 'New Detail', new_detail_path %>
<%#= link_to 'Generate Report', report_path(format: "pdf"), data: { no_turbolink: true, confirm: "Are you sure you want to generate today's report?" } %>

app/views/details/new.html.erb
<h1>New Detail</h1>

<%= render 'form', detail: @detail %>

app/views/details/show.html.erb
<%= render 'shared/page_title', title: "Date: #{@detail.date.strftime("%d/%m/%Y") if !@detail.date.nil?}" %>

<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description">
    <strong> Shop Name: <%= @detail.shop_name %> </strong>
  </h4>
  <hr />

  <div class="pull-left"> 
    <p class="center">
      <em>Customer Name:</em>
      <%= @detail.cust_name %>
    </p>

    <p class="center">
      <em>Phone:</em>
      <%= @detail.phone %>
    </p>

    <p class="center">
      <em>Address:</em>
      <%= @detail.address %>
    </p>

    <p class="center">
      <em>Status:</em>
      <%= @detail.status %>
    </p>

    
        
          <%= link_to 'Edit', edit_detail_path(@detail), class: "btn btn-primary" %> 
        
        
          <%= link_to 'Back', details_path, class: "btn btn-primary" %>
      
    
  </div>
</div>

app/views/layouts/_footer.html.erb
<hr>
<footer>
  <div class="container">
  	<center> <b>Hari Sarvothama Vaayu Jeevothama</b> </center>
    <p align="left">&copy; H.R. Ramesh</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <%= link_to "My Daily Reporter", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    
    <div>
      
    </div>
        
        <%= link_to "New Detail", new_detail_path, class: "btn btn-default" %> 
        <%= link_to "All Details", root_path, class: "btn btn-default" %> 
        <%= link_to 'Generate Today\'s Report', report_path(format: "pdf"), data: { no_turbolink: true, confirm: "Are you sure you want to generate today's report?" }, class: "btn btn-default gen" %>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Daily Reporter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, 'error') %>
            prohibited this <%= obj.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"> <%= title.capitalize %> </h1>
<hr />